export const compliments = [
  "You light up my world like fairy lights ✨",
  "You make everything better just by being you 🌍",
  "Your smile is pure sunshine to my soul ☀️",
  "You have the most beautiful heart 💫",
  "Your presence fills me with endless joy 🤗",
  "You're as magical as a shooting star 🌟",
  "Your laugh is the sweetest melody 😊",
  "You radiate love and warmth 🌈",
  "You're a masterpiece, perfectly imperfect 🎨",
  "Your heart is made of pure gold 💛",
  "You bring color to my every day 🌸",
  "You're stronger and more amazing than you know 💪",
  "Your energy lights up my entire world ⚡",
  "You make ordinary moments feel magical ✨",
  "You're my daily blessing 🙏",
  "Your existence is the greatest gift 🎁",
  "You have the power to heal hearts 🦋",
  "You're beautifully unique, my darling 🌺",
  "Your dreams are as valid as you are precious 🎯",
  "You deserve all the love in the universe 🌌",
  "You're exactly where my heart needs you to be 🗺️",
  "Your potential is as limitless as my love for you 🚀",
  "You make my heart flutter 💖",
  "You're loved more deeply than you'll ever know 💕",
  "You're absolutely perfect just as you are ⭐",
  "Your spirit shines brighter than any diamond 💎",
  "You have a heart full of pure magic 🪄",
  "You're the reason I smile every day 😄",
  "You create beauty in everything you touch 🌹",
  "You're made of stardust and love ✨",
  "Every moment with you feels like a dream 💭",
  "You're my favorite person in the whole world 🌎",
  "Your eyes hold all the stars I need to see 🌟",
  "You make my heart sing romantic melodies 🎵",
  "You're the sweetest love story ever written 📖"
];
